version: "3.8"

services:
  api:
    build: .
    container_name: aegis_api
    ports:
      - "18000:8000" # Un-popular port 18000
    environment:
      - DATABASE_URL=postgresql+asyncpg://aegis_user:aegis_pass@db:5432/aegis_db
      - REDIS_URL=redis://redis:6379/0
      - ENV=production
    depends_on:
      - db
      - redis
    networks:
      - aegis_net
    restart: always

  db:
    image: postgres:15-alpine
    container_name: aegis_db
    ports:
      - "15432:5432" # Un-popular port 15432
    environment:
      - POSTGRES_USER=aegis_user
      - POSTGRES_PASSWORD=aegis_pass
      - POSTGRES_DB=aegis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aegis_net

  redis:
    image: redis:7-alpine
    container_name: aegis_redis
    ports:
      - "16379:6379" # Un-popular port 16379
    networks:
      - aegis_net

  prometheus:
    image: prom/prometheus
    container_name: aegis_prom
    ports:
      - "19090:9090" # Un-popular port 19090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - aegis_net

networks:
  aegis_net:
    driver: bridge

volumes:
  postgres_data:
